import { highlightFontSize, LINE_HEIGHT } from './style';
import type { DisplayEvent, RenderSpec, SegmentStyle } from './types';

/** #RRGGBB -> &H00BBGGRR (ASS colors are little-endian BGR). */
export function hexToAssBgr(hex: string): string {
  const m = /^#([0-9a-fA-F]{6})$/.exec(hex);
  if (!m) throw new Error(`Invalid hex color: ${hex}`);
  const rgb = m[1]!;
  const r = rgb.slice(0, 2);
  const g = rgb.slice(2, 4);
  const b = rgb.slice(4, 6);
  return `&H00${b}${g}${r}`.toUpperCase();
}

/** Seconds -> H:MM:SS.cc. Start timestamps floor, end timestamps ceil (1 cs overlaps are harmless — the later event wins). */
export function assTimestamp(sec: number, ceil = false): string {
  const cs = Math.max(0, ceil ? Math.ceil(sec * 100) : Math.floor(sec * 100));
  const totalSec = Math.floor(cs / 100);
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor(totalSec / 60) % 60;
  const s = totalSec % 60;
  const cc = cs % 100;
  return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cc).padStart(2, '0')}`;
}

/** Escape ASS override-significant characters in caption text. */
export function escapeAssText(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\{/g, '\\{').replace(/\}/g, '\\}');
}

/**
 * Convert an outline width in video px to ASS \bord units. libass follows the
 * VSFilter convention of scaling border widths relative to a 288px-tall
 * reference, so units = px * 288 / PlayResY. Centralized here — the one place
 * to adjust if empirical verification disagrees.
 */
export function assOutlineUnits(outlineWidthPx: number, playResY: number): number {
  return Math.max(0, Math.round((outlineWidthPx * 288) / playResY));
}

const round1 = (n: number): string => String(Math.round(n * 10) / 10);

/**
 * Build the Text field for one event, breaking wrapped blocks into lines and
 * inserting override tags at the flagged spans.
 *
 * Line/highlight events carry the segment's whole block, so its lines are
 * split on '\n' and every line after the first is prefixed `\N{\pos(cx,y_i)\an8}`:
 * the dialogue's own prefix anchors line 0, and each further line re-anchors
 * itself at its line's top edge — the same pitch the overlay's line box uses
 * (fontSize * LINE_HEIGHT). A later `\pos` simply moves the pen, so no repeated
 * `\an8` would strictly be needed, but each line carries its own for clarity.
 *
 * The spoken word in 'highlight' mode is recolored, forced bold and enlarged —
 * the same emphasis the preview overlay draws (\fs is absolute, so the base
 * size and weight are restored right after the span).
 */
function buildEventText(e: DisplayEvent): string {
  const { style } = e;
  const hl = hexToAssBgr(style.highlightColor);
  const base = hexToAssBgr(style.color);
  const hlSize = highlightFontSize(style.fontSize);
  const baseBold = style.fontWeight >= 700 ? 1 : 0;
  const isHighlight = e.mode === 'highlight';

  let out = '';
  let lineStart = 0;
  e.text.split('\n').forEach((line, i) => {
    if (i > 0) {
      const y = e.y + i * style.fontSize * LINE_HEIGHT;
      out += `\\N{\\pos(${round1(e.x)},${round1(y)})\\an8}`;
    }
    const esc = escapeAssText(line);
    if (!isHighlight) {
      out += esc;
    } else {
      // Spans were resolved against the whole block; wrapping never splits a
      // word, so each lies within one line and is applied with the line's start
      // subtracted. (Pre-existing quirk: they index the *escaped* line, so a
      // word containing '{' or '\' shifts the spans after it on that line.)
      let pos = 0;
      for (const w of e.words) {
        const start = Math.max(w.charStart - lineStart, 0);
        const end = Math.min(w.charEnd - lineStart, line.length);
        if (end <= start) continue; // belongs to another line
        out += esc.slice(pos, start);
        if (w.highlighted) {
          out += `{\\c${hl}\\b1\\fs${hlSize}}${esc.slice(start, end)}{\\c${base}\\b${baseBold}\\fs${style.fontSize}}`;
        } else {
          out += esc.slice(start, end);
        }
        pos = end;
      }
      out += esc.slice(pos);
    }
    lineStart += line.length + 1; // +1 for the '\n' that followed it
  });
  return out;
}

/**
 * Generate a complete ASS document for the render spec. The editor has already
 * computed every line break and position, so libass performs no wrapping and
 * minimal layout (WrapStyle 2, hard breaks, per-event \pos with \an8).
 */
export function generateAss(spec: RenderSpec): string {
  const { video, segments } = spec;
  const out: string[] = [];
  out.push('[Script Info]');
  out.push('; Generated by captioner');
  out.push('ScriptType: v4.00+');
  out.push(`PlayResX: ${Math.round(video.width)}`);
  out.push(`PlayResY: ${Math.round(video.height)}`);
  out.push('ScaledBorderAndShadow: yes');
  out.push('WrapStyle: 2');
  out.push('');

  out.push('[V4+ Styles]');
  out.push(
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
  );
  const styles = new Map<string, { name: string; style: SegmentStyle }>();
  let styleCounter = 0;
  const styleKey = (st: SegmentStyle) =>
    `${st.fontFamily}|${st.fontSize}|${st.fontWeight}|${st.color}|${st.outlineColor}|${st.outlineWidth}|${st.highlightColor}`;
  const styleNameOf = (st: SegmentStyle): string => {
    const key = styleKey(st);
    let entry = styles.get(key);
    if (!entry) {
      entry = { name: `st${styleCounter++}`, style: st };
      styles.set(key, entry);
    }
    return entry.name;
  };

  const allEvents = segments
    .flatMap((seg) => seg.events.map((e) => ({ e, seg })))
    .sort((a, b) => a.e.start - b.e.start);

  // Collect styles first so [V4+ Styles] precedes [Events].
  for (const { e } of allEvents) styleNameOf(e.style);

  for (const { name, style: st } of styles.values()) {
    out.push(
      `Style: ${name},${st.fontFamily},${st.fontSize},${hexToAssBgr(st.color)},${hexToAssBgr(
        st.highlightColor,
      )},${hexToAssBgr(st.outlineColor)},&H80000000,${st.fontWeight >= 700 ? -1 : 0},0,0,0,100,100,0,0,1,${assOutlineUnits(
        st.outlineWidth,
        video.height,
      )},0,8,0,0,0,1`,
    );
  }
  out.push('');

  out.push('[Events]');
  out.push('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text');
  for (const { e } of allEvents) {
    const name = styleNameOf(e.style);
    const prefix = `{\\pos(${round1(e.x)},${round1(e.y)})\\an8}`;
    out.push(
      `Dialogue: 0,${assTimestamp(e.start)},${assTimestamp(e.end, true)},${name},,0,0,0,,${prefix}${buildEventText(e)}`,
    );
  }
  return out.join('\n') + '\n';
}
