import type { DisplayEvent, RenderSpec, SegmentStyle } from './types';

/** #RRGGBB -> &H00BBGGRR (ASS colors are little-endian BGR). */
export function hexToAssBgr(hex: string): string {
  const m = /^#([0-9a-fA-F]{6})$/.exec(hex);
  if (!m) throw new Error(`Invalid hex color: ${hex}`);
  const rgb = m[1]!;
  const r = rgb.slice(0, 2);
  const g = rgb.slice(2, 4);
  const b = rgb.slice(4, 6);
  return `&H00${b}${g}${r}`.toUpperCase();
}

/** Seconds -> H:MM:SS.cc. Start timestamps floor, end timestamps ceil (1 cs overlaps are harmless — the later event wins). */
export function assTimestamp(sec: number, ceil = false): string {
  const cs = Math.max(0, ceil ? Math.ceil(sec * 100) : Math.floor(sec * 100));
  const totalSec = Math.floor(cs / 100);
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor(totalSec / 60) % 60;
  const s = totalSec % 60;
  const cc = cs % 100;
  return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cc).padStart(2, '0')}`;
}

/** Escape ASS override-significant characters in caption text. */
export function escapeAssText(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\{/g, '\\{').replace(/\}/g, '\\}');
}

/**
 * Convert an outline width in video px to ASS \bord units. libass follows the
 * VSFilter convention of scaling border widths relative to a 288px-tall
 * reference, so units = px * 288 / PlayResY. Centralized here — the one place
 * to adjust if empirical verification disagrees.
 */
export function assOutlineUnits(outlineWidthPx: number, playResY: number): number {
  return Math.max(0, Math.round((outlineWidthPx * 288) / playResY));
}

const round1 = (n: number): string => String(Math.round(n * 10) / 10);

/** Build the Text field for one event, inserting highlight color override tags at the flagged spans. */
function buildEventText(e: DisplayEvent): string {
  const esc = escapeAssText(e.text);
  if (e.mode !== 'highlight') return esc;
  const hl = hexToAssBgr(e.style.highlightColor);
  const base = hexToAssBgr(e.style.color);
  let out = '';
  let pos = 0;
  for (const w of e.words) {
    out += esc.slice(pos, w.charStart);
    if (w.highlighted) {
      out += `{\\c${hl}}${esc.slice(w.charStart, w.charEnd)}{\\c${base}}`;
    } else {
      out += esc.slice(w.charStart, w.charEnd);
    }
    pos = w.charEnd;
  }
  out += esc.slice(pos);
  return out;
}

/**
 * Generate a complete ASS document for the render spec. The editor has already
 * computed every line break and position, so libass performs no wrapping and
 * minimal layout (WrapStyle 2, hard breaks, per-event \pos with \an8).
 */
export function generateAss(spec: RenderSpec): string {
  const { video, segments } = spec;
  const out: string[] = [];
  out.push('[Script Info]');
  out.push('; Generated by captioner');
  out.push('ScriptType: v4.00+');
  out.push(`PlayResX: ${Math.round(video.width)}`);
  out.push(`PlayResY: ${Math.round(video.height)}`);
  out.push('ScaledBorderAndShadow: yes');
  out.push('WrapStyle: 2');
  out.push('');

  out.push('[V4+ Styles]');
  out.push(
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
  );
  const styles = new Map<string, { name: string; style: SegmentStyle }>();
  let styleCounter = 0;
  const styleKey = (st: SegmentStyle) =>
    `${st.fontFamily}|${st.fontSize}|${st.color}|${st.outlineColor}|${st.outlineWidth}`;
  const styleNameOf = (st: SegmentStyle): string => {
    const key = styleKey(st);
    let entry = styles.get(key);
    if (!entry) {
      entry = { name: `st${styleCounter++}`, style: st };
      styles.set(key, entry);
    }
    return entry.name;
  };

  const allEvents = segments
    .flatMap((seg) => seg.events.map((e) => ({ e, seg })))
    .sort((a, b) => a.e.start - b.e.start);

  // Collect styles first so [V4+ Styles] precedes [Events].
  for (const { e } of allEvents) styleNameOf(e.style);

  for (const { name, style: st } of styles.values()) {
    out.push(
      `Style: ${name},${st.fontFamily},${st.fontSize},${hexToAssBgr(st.color)},${hexToAssBgr(
        st.highlightColor,
      )},${hexToAssBgr(st.outlineColor)},&H80000000,0,0,0,0,100,100,0,0,1,${assOutlineUnits(
        st.outlineWidth,
        video.height,
      )},0,8,0,0,0,1`,
    );
  }
  out.push('');

  out.push('[Events]');
  out.push('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text');
  for (const { e } of allEvents) {
    const name = styleNameOf(e.style);
    const prefix = `{\\pos(${round1(e.x)},${round1(e.y)})\\an8}`;
    out.push(
      `Dialogue: 0,${assTimestamp(e.start)},${assTimestamp(e.end, true)},${name},,0,0,0,,${prefix}${buildEventText(e)}`,
    );
  }
  return out.join('\n') + '\n';
}
