import { describe, expect, it } from 'vitest';
import {
  assOutlineUnits,
  assTimestamp,
  escapeAssText,
  generateAss,
  hexToAssBgr,
} from '../src/ass';
import { eventsForSegment, resolveSegmentLayout } from '../src/layout';
import { DEFAULT_BOX } from '../src/style';
import type { ExportSegment, RenderSpec, Segment, SegmentStyle } from '../src/types';

const styleA: SegmentStyle = {
  fontFamily: 'Arial',
  fontSize: 64,
  fontWeight: 700,
  color: '#FFFFFF',
  outlineColor: '#000000',
  outlineWidth: 4,
  highlightColor: '#FFD400',
};
const styleB: SegmentStyle = {
  fontFamily: 'Arial',
  fontSize: 48,
  fontWeight: 400,
  color: '#00FF00',
  outlineColor: '#FF0000',
  outlineWidth: 0,
  highlightColor: '#FFFFFF',
};

// fontSize-64 text: 40px per char; fontSize-48 text: 30px per char
const measure = (t: string, st: SegmentStyle) => t.length * (st.fontSize === 64 ? 40 : 30);

describe('ass helpers', () => {
  it('assTimestamp floors start and ceils end', () => {
    expect(assTimestamp(0)).toBe('0:00:00.00');
    expect(assTimestamp(1.5)).toBe('0:00:01.50');
    expect(assTimestamp(65.005)).toBe('0:01:05.00');
    expect(assTimestamp(0.005, true)).toBe('0:00:00.01');
    expect(assTimestamp(3601.99)).toBe('1:00:01.99');
  });

  it('hexToAssBgr converts and swaps channels', () => {
    expect(hexToAssBgr('#FFD400')).toBe('&H0000D4FF');
    expect(hexToAssBgr('#FFFFFF')).toBe('&H00FFFFFF');
    expect(hexToAssBgr('#00FF00')).toBe('&H0000FF00');
    expect(() => hexToAssBgr('red')).toThrow();
  });

  it('escapeAssText escapes braces and backslashes', () => {
    expect(escapeAssText('a{b}c')).toBe('a\\{b\\}c');
    expect(escapeAssText('back\\slash')).toBe('back\\\\slash');
  });

  it('assOutlineUnits scales by the 288px VSFilter reference', () => {
    expect(assOutlineUnits(4, 1920)).toBe(1);
    expect(assOutlineUnits(0, 1920)).toBe(0);
    expect(assOutlineUnits(6, 1080)).toBe(2);
  });
});

describe('generateAss', () => {
  it('produces a full document matching the golden output', () => {
    const seg1: Segment = {
      id: 's1',
      wordIds: ['w1', 'w2'],
      start: 0,
      end: 1.0,
      mode: 'word',
      style: styleA,
      box: { x: 100, y: 1400, width: 800 },
    };
    const seg2: Segment = {
      id: 's2',
      wordIds: ['w3', 'w4'],
      start: 1.5,
      end: 2.5,
      mode: 'highlight',
      style: styleB,
      box: { x: 0, y: 0, width: 500 },
    };
    const words = [
      { id: 'w1', text: 'hello', start: 0, end: 0.5 },
      { id: 'w2', text: 'world', start: 0.5, end: 1.0 },
      { id: 'w3', text: 'bye', start: 1.5, end: 2.0 },
      { id: 'w4', text: 'now', start: 2.0, end: 2.5 },
    ];

    const spec: RenderSpec = {
      version: 1,
      renderer: 'ass',
      video: { name: 't.mp4', duration: 2.5, width: 1080, height: 1920 },
      segments: [seg1, seg2].map((seg) => {
        const segWords = seg.wordIds.map((id) => words.find((w) => w.id === id)!);
        return resolveSegmentLayout(seg, segWords, (t) => measure(t, seg.style), DEFAULT_BOX);
      }),
      fonts: [],
      output: { videoCodec: 'libx264', crf: 18, preset: 'veryfast', audioCodec: 'aac', audioBitrate: '192k' },
    };

    const ass = generateAss(spec);
    expect(ass).toBe(`[Script Info]
; Generated by captioner
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: st0,Arial,64,&H00FFFFFF,&H0000D4FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,1,0,8,0,0,0,1
Style: st1,Arial,48,&H0000FF00,&H00FFFFFF,&H000000FF,&H80000000,0,0,0,0,100,100,0,0,1,0,0,8,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:00.50,st0,,0,0,0,,{\\pos(380,1400)\\an8}hello
Dialogue: 0,0:00:00.50,0:00:01.00,st0,,0,0,0,,{\\pos(620,1400)\\an8}world
Dialogue: 0,0:00:01.50,0:00:02.00,st1,,0,0,0,,{\\pos(250,0)\\an8}{\\c&H00FFFFFF\\b1\\fs54}bye{\\c&H0000FF00\\b0\\fs48} now
Dialogue: 0,0:00:02.00,0:00:02.50,st1,,0,0,0,,{\\pos(250,0)\\an8}bye {\\c&H00FFFFFF\\b1\\fs54}now{\\c&H0000FF00\\b0\\fs48}
`);
  });

  it('emphasizes the spoken word and restores the base weight and size after it', () => {
    // styleA is already bold (700), so the restore tag must keep it bold and
    // return to the base size (highlight size for 64px is 70).
    const seg: Segment = {
      id: 's1',
      wordIds: ['w1'],
      start: 0,
      end: 1,
      mode: 'highlight',
      style: styleA,
      box: { x: 0, y: 0, width: 800 },
    };
    const word = { id: 'w1', text: 'loud', start: 0, end: 1 };
    const layout = resolveSegmentLayout(seg, [word], (t) => t.length * 40, DEFAULT_BOX);
    const ass = generateAss({
      version: 1,
      renderer: 'ass',
      video: { name: 't.mp4', duration: 1, width: 1080, height: 1920 },
      segments: [layout],
      fonts: [],
      output: { videoCodec: 'libx264', crf: 18, preset: 'veryfast', audioCodec: 'aac', audioBitrate: '192k' },
    });
    expect(ass).toContain('{\\c&H0000D4FF\\b1\\fs70}loud{\\c&H00FFFFFF\\b1\\fs64}');
  });

  it('gives styles that differ only in weight or highlight color their own Style line', () => {
    const make = (weight: number, highlight: string): Segment => ({
      id: `s${weight}-${highlight}`,
      wordIds: ['w1'],
      start: 0,
      end: 1,
      mode: 'word',
      style: { ...styleA, fontWeight: weight, highlightColor: highlight },
      box: { x: 0, y: 0, width: 800 },
    });
    const word = { id: 'w1', text: 'hi', start: 0, end: 1 };
    const segs = [make(700, '#FFD400'), make(800, '#FFD400'), make(700, '#00FF00')];
    const ass = generateAss({
      version: 1,
      renderer: 'ass',
      video: { name: 't.mp4', duration: 1, width: 1080, height: 1920 },
      segments: segs.map((s) => resolveSegmentLayout(s, [word], (t) => t.length * 40, DEFAULT_BOX)),
      fonts: [],
      output: { videoCodec: 'libx264', crf: 18, preset: 'veryfast', audioCodec: 'aac', audioBitrate: '192k' },
    });
    expect(ass.split('\n').filter((l) => l.startsWith('Style:'))).toHaveLength(3);
  });
});

describe('generateAss with a wrapped block', () => {
  // "hello there" is 440px in a 400px box: two lines. The block sits at the box
  // top; the second line re-anchors one line-height below it (64 * 1.2 = 76.8).
  const seg = (mode: Segment['mode']): Segment => ({
    id: 's1',
    wordIds: ['w1', 'w2'],
    start: 0,
    end: 1,
    mode,
    style: styleA,
    box: { x: 100, y: 1400, width: 400 },
  });
  const words = [
    { id: 'w1', text: 'hello', start: 0, end: 0.5 },
    { id: 'w2', text: 'there', start: 0.5, end: 1 },
  ];
  const dialoguesFor = (mode: Segment['mode']): string[] => {
    const layout: ExportSegment = resolveSegmentLayout(
      seg(mode),
      words,
      (t) => t.length * 40,
      DEFAULT_BOX,
    );
    const spec: RenderSpec = {
      version: 1,
      renderer: 'ass',
      video: { name: 't.mp4', duration: 1, width: 1080, height: 1920 },
      segments: [layout],
      fonts: [],
      output: { videoCodec: 'libx264', crf: 18, preset: 'veryfast', audioCodec: 'aac', audioBitrate: '192k' },
    };
    return generateAss(spec).split('\n').filter((l) => l.startsWith('Dialogue:'));
  };

  it('breaks the block with \\N and re-positions each further line', () => {
    expect(dialoguesFor('line')).toEqual([
      'Dialogue: 0,0:00:00.00,0:00:00.50,st0,,0,0,0,,{\\pos(300,1400)\\an8}hello\\N{\\pos(300,1476.8)\\an8}there',
      'Dialogue: 0,0:00:00.50,0:00:01.00,st0,,0,0,0,,{\\pos(300,1400)\\an8}hello\\N{\\pos(300,1476.8)\\an8}there',
    ]);
  });

  it('applies the emphasis inside the line the spoken word is on', () => {
    const dialogues = dialoguesFor('highlight');
    // Word 1 is on the first line, word 2 on the second.
    expect(dialogues[0]).toBe(
      'Dialogue: 0,0:00:00.00,0:00:00.50,st0,,0,0,0,,{\\pos(300,1400)\\an8}{\\c&H0000D4FF\\b1\\fs70}hello{\\c&H00FFFFFF\\b1\\fs64}\\N{\\pos(300,1476.8)\\an8}there',
    );
    expect(dialogues[1]).toBe(
      'Dialogue: 0,0:00:00.50,0:00:01.00,st0,,0,0,0,,{\\pos(300,1400)\\an8}hello\\N{\\pos(300,1476.8)\\an8}{\\c&H0000D4FF\\b1\\fs70}there{\\c&H00FFFFFF\\b1\\fs64}',
    );
  });
});
